from datetime import datetime, timedelta, timezone
from typing import Any

from loguru import logger

from stradegy.config import settings
from stradegy.engine.research.models import GemSignal


class TelegramAlertManager:
    def __init__(self):
        self._last_alert: dict[str, datetime] = {}
        self._last_daily_report: datetime | None = None
        self._bot = None

    def _ensure_bot(self):
        if self._bot is None:
            try:
                from telegram import Bot
                self._bot = Bot(token=settings.telegram_bot_token)
                logger.info("Telegram bot initialized")
            except Exception as e:
                logger.error(f"Failed to initialize Telegram bot: {e}")
                raise

    def _is_throttled(self, ticker: str) -> bool:
        last = self._last_alert.get(ticker.upper())
        if not last:
            return False
        return datetime.now(timezone.utc) - last < timedelta(hours=2)

    def _format_daily_pnl(self, data: dict[str, Any]) -> str:
        from datetime import date
        equity = data.get("equity", 0.0)
        day_pnl = data.get("day_pnl", 0.0)
        day_pnl_pct = data.get("day_pnl_pct", 0.0)
        open_positions = data.get("open_positions", 0)
        tax_reserve = data.get("tax_reserve", 0.0)

        pnl_emoji = "🟢" if day_pnl >= 0 else "🔴"
        pnl_sign = "+" if day_pnl >= 0 else ""

        lines = [
            f"📊 <b>DAILY P&L REPORT</b>",
            f"",
            f"Date: {date.today().isoformat()}",
            f"Equity: <b>${equity:,.2f}</b>",
            f"",
            f"{pnl_emoji} Day P&L: {pnl_sign}${day_pnl:,.2f} ({pnl_sign}{day_pnl_pct:.2f}%)",
            f"📈 Open Positions: {open_positions}",
            f"💰 Tax Reserve: ${tax_reserve:,.2f}",
            f"",
        ]

        positions = data.get("positions", [])
        if positions:
            lines.append("📋 Positions:")
            for pos in positions[:5]:
                pnl = pos.get("pnl", 0)
                pnl_emoji_pos = "🟢" if pnl >= 0 else "🔴"
                lines.append(
                    f"  {pnl_emoji_pos} ${pos['symbol']}: "
                    f"{pos['qty']} shares @ ${pos['avg_entry']:.2f} "
                    f"| P&L: ${pnl:,.2f}"
                )

        lines.append(f"")
        lines.append(f"<i>Stradegy Trading Bot</i>")

        return "\n".join(lines)

    def _format_trade_notification(self, trade: dict[str, Any]) -> str:
        side = trade.get("side", "")
        symbol = trade.get("symbol", "")
        qty = trade.get("qty", 0)
        price = trade.get("price", 0.0)
        total = trade.get("total", 0.0)

        emoji = "🟢" if side == "buy" else "🔴"
        action = "BOUGHT" if side == "buy" else "SOLD"

        return (
            f"{emoji} <b>TRADE EXECUTED</b>\n\n"
            f"{action}: <b>${symbol}</b>\n"
            f"Qty: {qty}\n"
            f"Price: ${price:.2f}\n"
            f"Total: ${total:,.2f}\n\n"
            f"<i>{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}</i>"
        )

    def _format_tax_reminder(self, data: dict[str, Any]) -> str:
        tax_owed = data.get("tax_owed", 0.0)
        short_term_gains = data.get("short_term_gains", 0.0)
        reserve = data.get("reserve", 0.0)

        return (
            f"⚠️ <b>TAX RESERVE REMINDER</b>\n\n"
            f"Short-term gains YTD: ${short_term_gains:,.2f}\n"
            f"Estimated tax owed (30%): ${tax_owed:,.2f}\n"
            f"Current reserve: ${reserve:,.2f}\n"
            f"Status: {'✅ Adequate' if reserve >= tax_owed else '❌ Under-funded'}\n\n"
            f"<i>Set aside 30% of all short-term gains. Never trade with tax money.</i>"
        )

    def _format_alert(self, gem: GemSignal) -> str:
        emoji = {
            "strong_gem": "🔥",
            "potential_gem": "💎",
            "watchlist": "👀",
            "discard": "🗑️",
        }.get(gem.classification.value, "📊")

        lines = [
            f"{emoji} <b>STRADEGY GEM ALERT</b>",
            f"",
            f"<b>${gem.ticker_symbol}</b> — {gem.classification.value.replace('_', ' ').title()}",
            f"Score: <b>{gem.total_score:.0f}/100</b> | Sources: {gem.source_count}",
            f"",
            f"📊 Breakdown:",
            f"  Reddit: {gem.reddit_score:.1f}/25",
            f"  Discord: {gem.discord_score:.1f}/25",
            f"  SEC: {gem.sec_score:.1f}/30",
            f"  News: {gem.news_score:.1f}/20",
            f"  Technical: {gem.technical_score:.1f}/25",
            f"",
        ]

        if gem.evidence_urls:
            lines.append("🔗 Evidence:")
            for url in gem.evidence_urls[:3]:
                lines.append(f"  • {url}")

        lines.append(f"")
        lines.append(f"<i>Generated by Stradegy at {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}</i>")

        return "\n".join(lines)

    async def send_gem_alert(self, gem: GemSignal) -> bool:
        if not settings.telegram_bot_token or not settings.telegram_chat_id:
            logger.warning("Telegram not configured, skipping alert")
            return False

        if self._is_throttled(gem.ticker_symbol):
            logger.info(f"Alert throttled for {gem.ticker_symbol}")
            return False

        try:
            self._ensure_bot()
            message = self._format_alert(gem)
            await self._bot.send_message(
                chat_id=settings.telegram_chat_id,
                text=message,
                parse_mode="HTML",
            )
            self._last_alert[gem.ticker_symbol.upper()] = datetime.now(timezone.utc)
            logger.info(f"Telegram alert sent for {gem.ticker_symbol}")
            return True
        except Exception as e:
            logger.error(f"Failed to send Telegram alert: {e}")
            return False

    async def send_daily_pnl(self, data: dict[str, Any]) -> bool:
        if not settings.telegram_bot_token or not settings.telegram_chat_id:
            return False

        if self._last_daily_report and \
           datetime.now(timezone.utc) - self._last_daily_report < timedelta(hours=20):
            return False

        try:
            self._ensure_bot()
            message = self._format_daily_pnl(data)
            await self._bot.send_message(
                chat_id=settings.telegram_chat_id,
                text=message,
                parse_mode="HTML",
            )
            self._last_daily_report = datetime.now(timezone.utc)
            logger.info("Daily P&L report sent")
            return True
        except Exception as e:
            logger.error(f"Failed to send daily P&L: {e}")
            return False

    async def send_trade_notification(self, trade: dict[str, Any]) -> bool:
        if not settings.telegram_bot_token or not settings.telegram_chat_id:
            return False

        try:
            self._ensure_bot()
            message = self._format_trade_notification(trade)
            await self._bot.send_message(
                chat_id=settings.telegram_chat_id,
                text=message,
                parse_mode="HTML",
            )
            logger.info(f"Trade notification sent for {trade.get('symbol')}")
            return True
        except Exception as e:
            logger.error(f"Failed to send trade notification: {e}")
            return False

    async def send_tax_reminder(self, data: dict[str, Any]) -> bool:
        if not settings.telegram_bot_token or not settings.telegram_chat_id:
            return False

        try:
            self._ensure_bot()
            message = self._format_tax_reminder(data)
            await self._bot.send_message(
                chat_id=settings.telegram_chat_id,
                text=message,
                parse_mode="HTML",
            )
            logger.info("Tax reminder sent")
            return True
        except Exception as e:
            logger.error(f"Failed to send tax reminder: {e}")
            return False
